FROM bitnamilegacy/spark:3.5.1

USER root

ENV PATH="/home/airflow/.local/bin:$PATH"
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system -r pyproject.toml


USER 1001
