
FROM gradle:8.5-jdk17 AS jar-builder

WORKDIR /builder
COPY build.gradle .

RUN gradle copyDependencies --no-daemon

FROM bitnamilegacy/spark:3.5.1

USER root

COPY --from=jar-builder /builder/build/deps/*.jar /opt/bitnami/spark/jars/

WORKDIR /app
ENV PATH="/home/airflow/.local/bin:$PATH"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY pyproject.toml uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --system -r pyproject.toml

USER 1001

WORKDIR /opt/bitnami/spark
