# k8s RBAC (ns: airflow -> spark-applications)
# Related SA: (airflow-sa, airflow-scheduler, airflow-triggerer, airflow-worker)
# Role: airflow-spark-editor
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-applications
  name: airflow-spark-editor
rules:
  - apiGroups: [ "sparkoperator.k8s.io" ]
    resources: [ "sparkapplications", "sparkapplications/status" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list", "watch", "create", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-spark-editor-binding
  namespace: spark-applications
subjects:
  - kind: ServiceAccount
    name: airflow-sa # Must match serviceAccount.name in airflow-values.yaml.yaml
    namespace: airflow
  - kind: ServiceAccount
    name: gitsight-airflow-scheduler
    namespace: airflow
  - kind: ServiceAccount
    name: gitsight-airflow-triggerer
    namespace: airflow
  - kind: ServiceAccount
    name: gitsight-airflow-airflow-worker
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-spark-editor
  apiGroup: rbac.authorization.k8s.io

