apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gitsight-airflow-updater
  namespace: argocd
spec:
  applicationRefs:
    - name: gitsight-airflow
      namespace: argocd

  images:
    - image: 10.43.7.183:5000/gitsight/airflow
      updateStrategy:
        name: digest
      pullPolicy: Always

  writeBack:
    method: git
