airflow:
  images:
    airflow:
      pullPolicy: IfNotPresent

  env:
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "False"
    - name: AIRFLOW__KUBERNETES__NAMESPACE
      value: "airflow"

  executor: LocalExecutor

  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: false

  logs:
    persistence:
      enabled: false

  statsd:
    enabled: false

  rbac:
    create: true

  serviceAccount:
    create: true
    name: "airflow-sa"
    annotations: { }


  triggerer:
    enabled: true

  postgresql:
    image:
      repository: bitnamilegacy/postgresql
      tag: "11"

  migrateDatabaseJob:
    enabled: true

  #airflowLocalSettings: |
  #  # Overriding default local settings to avoid airflow.www import errors in Airflow 3.x
  #  def policy(task_instance):
  #      pass

