#  kubectl annotate application gitsight-airflow -n argocd \
#    argocd-image-updater.argoproj.io/api-server.update-strategy=latest \
#    --overwrite

# to Debug: kubectl logs -n argocd -l app.kubernetes.io/name=argocd-image-updater -f --tail=20
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gitsight-airflow-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: gitsight-airflow
      useAnnotations: true
  writeBackConfig:
    method: git
