apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: minio-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
