name: Gitsight Airflow CI

on:
  pull_request:
    paths:
      - "k8s/ci/airflow-ci.yaml"
      - "docker/airflow/**"
      - "pyproject.toml"
      - "uv.lock"
    branches: [ "main" ]

jobs:
  airflow-ci:
    runs-on: ubuntu-latest
    steps:
      - name: SSH through Bastion and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USER }}
          key: ${{ secrets.OCI_KEY }}
          proxy_host: ${{ secrets.BASTION_HOST }}
          proxy_username: ${{ secrets.BASTION_USER }}
          proxy_key: ${{ secrets.OCI_KEY }}
          proxy_port: 22
          script: |
            cd ~/gitsight-data-pipeline
            git fetch --prune origin
            git reset --hard origin/dev
            
            export KUBECONFIG=$HOME/.kube/config
            
            kubectl delete job gitsight-airflow-ci-job -n zot --ignore-not-found
            kubectl apply -f k8s/ci/airflow-ci.yaml
            
            kubectl wait --for=condition=complete --timeout=900s job/gitsight-airflow-ci-job -n zot || (kubectl logs -n zot -l job-name=gitsight-airflow-ci-job --tail=100 && exit 1)
            
            kubectl get pods -n zot | grep -E 'gitsight-airflow-ci-job'
